### ISSUE TITLE
AMI_PFAT_Extract not working with new METEORLAKE core ultra AMI BIOS Guard protected images

### ISSUE THREAD

**Issue by Anton-35** [platomav/BIOSUtilities#30]
ASUS released new Intel 14th gen Core Ultra ASUS Zenbook 14. 
https://www.asus.com/laptops/for-home/zenbook/asus-zenbook-14-oled-ux3405/techspec/

And AMI BIOS Guard Extractor v4.0_a12 not working with it's AMI BIOS Guard protected BIOS images. Showing many errors.
Error log: https://mega.nz/file/sTR3nLDD#K0fqlV8GorWfuubM3heOii0RHSIhvMca-LW9_UAPDvk
bios image: https://mega.nz/file/FapnAYKQ#HBuHEUFEHgq6f-XsYF7Tr7VKLCunhnk0CkePpOm1QS0

**Comment by aditya11ttt** [comment]
Original backup please

**Comment by Anton-35** [comment]
> Original backup please

I don't have a backup or a laptop. Meteor Lake laptops were released a few days ago.

**Comment by Anton-35** [comment]
I managed to find the original full dump for this notebook. It wasn't easy.
full dump v301: https://mega.nz/file/9GAinTjC#6Ot89QDTQbq8VoXFfYBGGUxCpbLnv5MzsorqEuLEWI0
asus bios update v301: https://mega.nz/file/sfR3BJzA#mOv6_PndVUKVq0Tk6jwABJiO0uxW3JPSQDeWL4XUdXg
I hope it will help in developing a new version of the script.

**Comment by platomav** [comment]
The problem occurs because the PFAT images of Meterolake platform use a stronger/larger RSA signature (3072-bits vs 2048-bits) after each signed data block.

I have already added support for RSA 3K signed blocks in a (currently) internal/wip build of the AMI PFAT Extractor utility, but have not really back-ported that enhancement to the old/main branch here. I'm not sure if I'll do that soon, to be honest, but I am attaching here the output of that Meteorlake image you provided. The issue will remain open until the fix is properly pushed to the repo, of course.

[UX3405MAAS.301_extracted_rar.zip](https://github.com/platomav/BIOSUtilities/files/13894207/UX3405MAAS.301_extracted_rar.zip)

**Comment by Anton-35** [comment]
Thanks, but i don't need extracted bios update image for this notebook if i already have a full dump. I needed a working version of AMI_PFAT_Extract script that would help unpack other bios update images. If you have a solution why not apply it? I don't quite understand this.

**Comment by platomav** [comment]
Fixed at #38 (6ae1587)
